//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condom.Infra.Global {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CondomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CondomResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Condom.Infra.Global.CondomResources", typeof(CondomResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Source=tcp:condomdbserver.database.windows.net,1433;Initial Catalog=Condom_db;User Id=Condom@condomdbserver;Password=FIAP@2022.
        /// </summary>
        public static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///    {
        ///        &quot;name&quot;: &quot;Cantareira&quot;,
        ///        &quot;data&quot;: [
        ///            {
        ///                &quot;key&quot;: &quot;volume armazenado&quot;,
        ///                &quot;value&quot;: &quot;18,9 %&quot;
        ///            },
        ///            {
        ///                &quot;key&quot;: &quot;pluviometria do dia&quot;,
        ///                &quot;value&quot;: &quot;16,4 mm&quot;
        ///            },
        ///            {
        ///                &quot;key&quot;: &quot;pluviometria acumulada no mês&quot;,
        ///                &quot;value&quot;: &quot;206,3 mm&quot;
        ///            },
        ///            {
        ///                &quot;key&quot;: &quot;média histórica do mês&quot;,
        ///                &quot;value&quot;: &quot;178,0 mm&quot;
        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SabespMock {
            get {
                return ResourceManager.GetString("SabespMock", resourceCulture);
            }
        }
    }
}
